# Generated by Django 5.0.6 on 2024-07-30 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSugar', '0002_reservas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='entregado',
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='reserva',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='pedido',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservas',
            name='horario',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
